name: Build BadApple


on:
  push:
    branches: 
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          choco install libpng -y
          refreshenv

      - name: Build solution
        shell: pwsh
        run: |
          $vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
          $vsPath = & $vswhere -latest -products * -requires Microsoft.Component.MSBuild -property installationPath
          $msbuild = Join-Path $vsPath "MSBuild\Current\Bin\MSBuild.exe"
          & $msbuild BadApple.sln /p:Configuration=Release /p:Platform=x64
