name: Build BadApple

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Install libpng
        run: choco install libpng -y

      - name: Build solution
        run: msbuild BadApple.sln /p:Configuration=Release /p:Platform=x64
